In [1]:
import SelectkClassification
import SelectkRegression

In [2]:
classificationResult = SelectkClassification.selectk_ClassificationResult()
classificationResult

          Logistic  SVMl SVMnl   KNN Naive Decision Random
ChiSquare     0.94  0.94  0.95  0.89  0.83     0.96   0.95

In [3]:
regressionResult = SelectkRegression.selectKRegressionResult()
regressionResult

             Linear      SVMl     SVMnl  Decision    Random
ChiSquare  0.551985  0.545395  0.749654  0.696181  0.836806