In [4]:
import RFE_Classification
import RFE_Regression

In [5]:
classification_result = RFE_Classification.rfe_classification_result()
classification_result

/Users/NYL9BJV/AI-Learning-Journey/my-ai-learning-lab/adv-machine-learning/RFE/RFE_Classification.py:114: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rfedataframe['Logistic'][idex]=acclog[number]
/Users/NYL9BJV/AI-Learning-Journey/my-ai-learning-lab/adv-machine-learning/RFE/RFE_Classification.py:115: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rfedataframe['SVMl'][idex]=accsvml[number]
/Users/NYL9BJV/AI-Learning-Journey/my-ai-learning-lab/adv-machine-learning/RFE/RFE_Classification.py:116: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rfedataframe['SVMnl'][idex]=accsvmnl[number]
/Users/NYL9BJV/AI-Learning-Journey/my-ai-learning-lab/adv-machine-learning/RFE/RFE_Classification.py:117: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rfedataframe['KNN'][idex]=accknn[number]
/Users/NYL9BJV/AI-Learning-Journey/my-ai-learning-lab/adv-machine-learning/RFE/RFE_Classification.py:118: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rfedataframe['Navie'][idex]=accnav[number]
/Users/NYL9BJV/AI-Learning-Journey/my-ai-learning-lab/adv-machine-learning/RFE/RFE_Classification.py:119: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rfedataframe['Decision'][idex]=accdes[number]
/Users/NYL9BJV/AI-Learning-Journey/my-ai-learning-lab/adv-machine-learning/RFE/RFE_Classification.py:120: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rfedataframe['Random'][idex]=accrf[number]

             Logistic  SVMl SVMnl   KNN Navie Decision Random
Logistic         0.98  0.98  0.99  0.99  0.91     0.99   0.99
SVC              0.97  0.98  0.98  0.98  0.75     0.93   0.97
Random           0.91  0.93  0.94  0.92  0.94     0.88   0.92
DecisionTree     0.99  0.96  0.96  0.99  0.78     0.99   0.99

In [6]:
regression_result = RFE_Regression.rfe_regression_result()
regression_result

LinearRegression()
SVR(kernel='linear')
DecisionTreeRegressor(random_state=0)
RandomForestRegressor(n_estimators=10, random_state=0)
                Linear       SVM  Decision    Random
Linear        0.441961  0.262153  0.441961  0.441816
SVM           0.441961  0.262153  0.441961  0.441816
DecisionTree  0.664893  0.609652  0.965961  0.916304
RandomForest  0.676174  0.670691  0.933504  0.887256

                Linear       SVM  Decision    Random
Linear        0.441961  0.262153  0.441961  0.441816
SVM           0.441961  0.262153  0.441961  0.441816
DecisionTree  0.664893  0.609652  0.965961  0.916304
RandomForest  0.676174  0.670691  0.933504  0.887256