In [6]:
import pandas as pd
import numpy as np
dataset = pd.read_csv("Placement.csv")

In [7]:
from Univariate import Univariate
obj = Univariate()

quan, qual = obj.quanQual(dataset)

In [8]:
print(quan)
print(qual)
dataset['ssc_p'].mean()

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']
['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex', 'specialisation', 'status']

np.float64(67.30339534883721)

In [9]:
descriptive=pd.DataFrame(index=["Mean", "Median", "Mode"], columns=quan)
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [10]:
descriptive=pd.DataFrame(index=["Mean", "Median", "Mode", "Q1:25%", "Q2:50%", "Q3:75%", "Q4:100%"], columns=quan)
for columnName in quan:
    descriptive.loc["Mean", columnName]=dataset[columnName].mean()
    descriptive.loc["Median", columnName]=dataset[columnName].median()
    descriptive.loc["Mode", columnName]=dataset[columnName].median()
    descriptive.loc["Q1:25%", columnName]=dataset[columnName].quantile(0.25)
    descriptive.loc["Q2:50%", columnName]=dataset[columnName].quantile(0.50)
    descriptive.loc["Q3:75%", columnName]=dataset[columnName].quantile(0.75)
    descriptive.loc["Q4:100%", columnName]=dataset[columnName].quantile(0.1)

descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,22.4,52.0,52.0,57.0,55.802,54.986,217400.0